################################
##   SANDBOX GLOBAL SETTINGS  ##
################################

sandbox_box: "chef/centos-6.5"

sandbox_memory: "3072"

sandbox_cpus: "2"

sandbox_max_cpu_usage: "60"

#################################
##   MODULE SPECIFIC SETTINGS  ##
#################################


######## STRATIO STREAMING ######

# environment, it should be [LOCAL|DEV|PRE|PRO]
stratio_env: "PRE"

# this module will be fully installed in the sandbox
# always write the full github url (including /tree/branch)
stratio_module_repository: "https://github.com/Stratio/streaming-cep-engine/tree/master"

# this optional parameter will be the final version of the module
# if not present, we will try to retrieve the version from the github url 
stratio_module_version: "0.5.0"

######## STRATIO CROSSDATA ######



######## STRATIO DEEP ######


######## STRATIO DATAVIS ######



######## STRATIO ADMIN ######


######## STRATIO SPARKTA ######
